version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: scjtqs:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: feature/v2            # Required. Target branch
    upstream: scjtqs:feature/v2     # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: feature/v1            # Required. Target branch
    upstream: scjtqs:feature/v1     # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
#  - base: dev
#    upstream: master        # Required. Can be a branch in the same forked repo.
#    assignees:              # Optional
#      - wei
#    reviewers:              # Optional
#      - wei
#    conflictReviewers:      # Optional, on merge conflict assign a reviewer
#      - wei
#label: ":arrow_heading_down: pull"  # Optional
#conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
