kind: pipeline
type: docker
name: default

clone:
  depth: 1
  disable: true

steps:
  # 从github拉取代码 加上代理
  - name: clone
    image: alpine/git
    pull: if-not-exists
#    environment:
#      https_proxy:
#        from_secret: http_proxy
#      http_proxy:
#        from_secret: http_proxy
#      all_proxy:
#        from_secret: socket_proxy
    commands:
      - git clone --depth 1 https://hub.fastgit.org/scjtqs/jd_cookie.git .
      - "[ ''$DRONE_BRANCH'' != 'master' ] &&  [ ''$DRONE_BANCH'' != 'main' ] && git switch -c ''$DRONE_BRANCH''"
#      - git checkout $DRONE_COMMIT
        
  - name: buildtest
    image: golang:1.16
    pull: if-not-exists
    environment:
      GOPROXY: "http://goproxy.cn,direct"
      CGO_ENABLED: 0
      GO111MODULE: "on"
    commands:
      - go get -u github.com/gobuffalo/packr/v2/packr2
      - go mod tidy
      - go build
    depends_on:
      - clone

  # go build
  - name: build
    image: golang:1.16
    pull: if-not-exists
    environment:
      GOPROXY: "http://goproxy.cn,direct"
      CGO_ENABLED: 0
      GO111MODULE: "on"
    commands:
      - go get -u github.com/gobuffalo/packr/v2/packr2
      - go mod tidy
      - GOOS=windows GOARCH=386         packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_windows_i386.exe
      - GOOS=windows GOARCH=amd64       packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_windows_adm64.exe
      - GOOS=windows GOARCH=arm GOARM=7 packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_windows_arm64.exe
      - GOOS=darwin GOARCH=arm64        packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_darwin_arm64
      - GOOS=darwin GOARCH=amd64        packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_darwin_amd64
      - GOOS=linux GOARCH=386           packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_linux_i386
      - GOOS=linux GOARCH=amd64         packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_linux_amd64
      - GOOS=linux GOARCH=arm   GOARM=7 packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_linux_armv7
      - GOOS=linux GOARCH=arm64         packr2 build  -ldflags  '-w -s' -o dist/jdcookie_v2_linux_arm64
    depends_on:
      - clone
    when:
      event: tag

  # 发布github的resease
  - name: publish
    image: plugins/github-release
    pull: if-not-exists
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
#      title: v1.0.0
#      note:  "第一个公开版本，只提取cookie，不带推送更新cookie到服务器"
#      draft: true
#      overwrite: true
    when:
      event: tag
    depends_on:
      - build

trigger:
#  branch:
#    - master
  event:
    - custom
    - push
    - cron
    - tag
