kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: golang:1.16
    environment:
      GOPROXY: "http://goproxy.cn,direct"
      CGO_ENABLED: 0
    commands:
      - go get -u github.com/gobuffalo/packr/v2/packr2
      - go mod tidy
      - GOOS=windows GOARCH=386   packr2 build -ldflags '-extldflags "-static"' -o dist/jdcookie_windows_i386.exe
      - GOOS=windows GOARCH=amd64 packr2 build -ldflags '-extldflags "-static"' -o dist/jdcookie_windows_adm64.exe
      - GOOS=windows GOARCH=arm64 packr2 build -ldflags '-extldflags "-static"' -o dist/jdcookie_windows_arm64.exe
      - GOOS=darwin GOARCH=arm64  packr2 build -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_darwin_arm64
      - GOOS=darwin GOARCH=amd64  packr2 build -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_darwin_amd64
      - GOOS=linux GOARCH=386     packr2 build  -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_linux_i386
      - GOOS=linux GOARCH=amd64   packr2 build -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_linux_amd64
      - GOOS=linux GOARCH=arm GOARM=7  packr2 build  -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_linux_armv7
      - GOOS=linux GOARCH=arm64   packr2 build -ldflags -w -s '-extldflags "-static"' -o dist/jdcookie_linux_arm64

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    when:
      event: tag
    depends_on:
      - build