#!/usr/bin/with-contenv bash

refresh_cron () {
    if [[ $(cat $JD_DIR/config/crontab.list) != $(crontab -l) ]]; then
        echo "检测到$JD_DIR/config/crontab.list有变化，立即刷新定时任务..."
        crontab $JD_DIR/config/crontab.list
    fi
}

run_parallel () {
    echo -e "\n======================== 启动定时任务自动刷新程序 ========================\n"
    echo -e "每2秒检测一次$JD_DIR/config/crontab.list是否发生变化，如发生变化则立即刷新定时任务。\n"
    yes | perl /usr/bin/parallel -N0 -j1 --delay 2s refresh_cron
}

export -f refresh_cron
run_parallel | perl -pe "s|^(.+)|[services.d] \1|g"