version: "2.2"
services:
  lys:
    container_name: lys
    image: huanghyw/jd-seckill:latest
    build:
      context: ../dockerfile
      dockerfile: Dockerfile
    env_file:
      - ../dockerfile/docker.env
    volumes: 
      - ../logs_volumes/lys:/logs
      - ../cookies_volumes/lys:/cookies