name: jd_py #action名字，随便起 
env:
  ID: jd_py
  URL: https://github.com/ClassmateLin/jd_scripts.git
  BRANCH: master
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: sync
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x      
      - name: '运行同步'
        run: |
          git clone ${URL} tmp
          rm -rf .git*
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${ID}