name: jd_py #action名字，随便起 
env:
  ID: jd_py
  URL: https://github.com/ClassmateLin/jd_scripts.git
  BRANCH: main
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: sync
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x      
      - name: '运行同步'
        run: |
          git clone -b ${BRANCH} ${URL} tmp
          rm -rf tmp/.git
          mv tmp/* /home/runner/work/script/script/
          rm -rf tmp
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update" -a || echo "Nothing to update"
          git remote set-url origin https://${{ secrets.PAT }}:x-oauth-basic@github.com/EVAyo/script.git
          git push -u origin ${ID}
          git push origin ${ID}
